// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface IUserChart {
	login: string;
	id: number;
	avatar_url: string;
	site_admin: boolean;
	contributions: number;
}