import { IUserData } from './IUserData';
// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface IDecoratedCommit {
    sha:          string;
    node_id:      string;
    commit:       ICommit;
    html_url:     string;
    author:       IUserData;
    committer:    IUserData;
    // parents:      Parent[];
    // stats:        Stats;
    // files:        File[];
}

export interface ICommit {
    author:        ICommitAuthor;
    committer:     ICommitAuthor;
    message:       string;
}

export interface ICommitAuthor {
    name:  string;
    email: string;
    date:  string;
}

/*
export interface File {
    sha:          string;
    filename:     string;
    status:       string;
    additions:    number;
    deletions:    number;
    changes:      number;
    blob_url:     string;
    raw_url:      string;
    contents_url: string;
    patch:        string;
}

export interface Parent {
    sha:      string;
    url:      string;
    html_url: string;
}

export interface Stats {
    total:     number;
    additions: number;
    deletions: number;
}
*/